[workspace]
members = [
  "misskey",
  "misskey-api",
  "misskey-core",
  "misskey-util",
  "misskey-http",
  "misskey-websocket",
  "misskey-test",
  "example/streaming",
  "example/ping-pong",
  "example/upload-file",
  "example/create-note",
  "example/word-reply",
  "example/follow-back",
]
