[package]
name = "misskey-api"
version = "0.1.0"
authors = ["coord.e <me@coord-e.com>"]
edition = "2018"

[dependencies]
misskey-core = { path = "../misskey-core" }
serde = { version = "1.0.103", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
url = { version = "2.1", features = ["serde"] }
async-trait = "0.1.35"
derive_more = "0.99.5"
strum_macros = "0.19"

[dev-dependencies]
misskey-http = { path = "../misskey-http" }
tokio = { version = "0.2.22", features = ["macros"] }
