[package]
name = "misskey-api"
version = "0.1.0"
authors = ["coord.e <me@coord-e.com>"]
edition = "2018"

[features]
default = ["12-40-0"]

12-40-0 = ["12-19-0"]
12-19-0 = ["12-10-0"]
12-10-0 = ["12-8-0"]
12-8-0 = []

[dependencies]
misskey-core = { path = "../misskey-core" }
serde = { version = "1.0.103", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
url = { version = "2.1", features = ["serde"] }
async-trait = "0.1.35"
derive_more = "0.99.5"
strum_macros = "0.19"

[dev-dependencies]
misskey-http = { path = "../misskey-http" }
tokio = { version = "0.2.22", features = ["macros"] }
uuid = { version = "0.8.1", features = ["v4"] }
lazy_static = "1.4.0"
mime = "0.3"
