[package]
name = "misskey-http"
version = "0.1.0"
authors = ["coord.e <me@coord-e.com>"]
edition = "2018"

[dependencies]
misskey-core = { path = "../misskey-core" }
serde_json = "1.0"
derive_more = "0.99.5"
url = "2.1"
reqwest = "0.10"
mime = "0.3"
async-trait = "0.1.35"
