[package]
name = "misskey-http"
version = "0.1.0"
authors = ["coord.e <me@coord-e.com>"]
edition = "2018"

[dependencies]
misskey = { path = "../misskey" }
serde_json = "1.0"
err-derive = "0.2.4"
url = "2.1.1"
reqwest = "0.10.6"
async-trait = "0.1.36"
