on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 5"

name: CI

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - nightly
          - beta
          - stable
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ubuntu-18.04-${{ matrix.toolchain }}-cargo-all-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ubuntu-18.04-${{ matrix.toolchain }}-cargo-all-
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --tests
      - id: setup_env
        run: ./ci/testenv/setup.sh
        env:
          MISSKEY_VERSION: latest
      - uses: actions-rs/cargo@v1
        timeout-minutes: 5
        env:
          TEST_API_URL: http://localhost:3000/api/
          TEST_WEBSOCKET_URL: ws://localhost:3000/streaming
          TEST_ADMIN_TOKEN: ${{ steps.setup_env.outputs.admin_token }}
          TEST_USER_TOKEN: ${{ steps.setup_env.outputs.user_token }}
        with:
          command: test
  test_api:
    name: Test misskey-api
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - version: '12.47.1'
            flags: --no-default-features --features 12-47-0
          - version: '12.40.0'
            flags: --no-default-features --features 12-39-0
          - version: '12.39.0'
            flags: --no-default-features --features 12-39-0
          - version: '12.30.0'
            flags: --no-default-features --features 12-29-0
          - version: '12.28.0'
            flags: --no-default-features --features 12-27-0
          - version: '12.20.0'
            flags: --no-default-features --features 12-19-0
          - version: '12.13.0'
            flags: --no-default-features --features 12-13-0
          - version: '12.10.0'
            flags: --no-default-features --features 12-10-0
          - version: '12.9.0'
            flags: --no-default-features --features 12-9-0
          - version: '12.8.0'
            flags: --no-default-features --features 12-8-0
          - version: '12.5.0'
            flags: --no-default-features --features 12-5-0
          - version: '12.0.0'
            flags: --no-default-features
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ubuntu-18.04-stable-cargo-misskey-api-${{ hashFiles('misskey-*/Cargo.toml') }}
          restore-keys: |
            ubuntu-18.04-stable-cargo-misskey-api-
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --tests --manifest-path misskey-api/Cargo.toml ${{ matrix.flags }}
      - id: setup_env
        run: ./ci/testenv/setup.sh
        env:
          MISSKEY_VERSION: ${{ matrix.version }}
      - uses: actions-rs/cargo@v1
        timeout-minutes: 5
        env:
          TEST_API_URL: http://localhost:3000/api/
          TEST_WEBSOCKET_URL: ws://localhost:3000/streaming
          TEST_ADMIN_TOKEN: ${{ steps.setup_env.outputs.admin_token }}
          TEST_USER_TOKEN: ${{ steps.setup_env.outputs.user_token }}
        with:
          command: test
          args: --manifest-path misskey-api/Cargo.toml ${{ matrix.flags }}
  test_websocket:
    name: Test misskey-websocket
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    strategy:
      matrix:
        features:
          - tokio-runtime
          - async-std-runtime
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ubuntu-18.04-stable-cargo-misskey-websocket-${{ hashFiles('misskey-*/Cargo.toml', '!misskey-http/Cargo.toml') }}
          restore-keys: |
            ubuntu-18.04-stable-cargo-misskey-websocket-
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --tests --manifest-path misskey-websocket/Cargo.toml --no-default-features --features ${{ matrix.features }}
      - id: setup_env
        run: ./ci/testenv/setup.sh
        env:
          MISSKEY_VERSION: 12.0.0
      - uses: actions-rs/cargo@v1
        timeout-minutes: 3
        env:
          TEST_WEBSOCKET_URL: ws://localhost:3000/streaming
          TEST_USER_TOKEN: ${{ steps.setup_env.outputs.user_token }}
        with:
          command: test
          args: --manifest-path misskey-websocket/Cargo.toml --no-default-features --features ${{ matrix.features }}
  fmt:
    name: Rustfmt
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
