on: [push, pull_request]

name: CI

jobs:
  test_api:
    name: Test misskey-api
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - version: '12.46.0'
            flags: ''
          - version: '12.40.0'
            flags: --no-default-features --features 12-39-0
          - version: '12.39.0'
            flags: --no-default-features --features 12-39-0
          - version: '12.30.0'
            flags: --no-default-features --features 12-29-0
          - version: '12.28.0'
            flags: --no-default-features --features 12-27-0
          - version: '12.20.0'
            flags: --no-default-features --features 12-19-0
          - version: '12.10.0'
            flags: --no-default-features --features 12-10-0
          - version: '12.9.0'
            flags: --no-default-features --features 12-9-0
          - version: '12.8.0'
            flags: --no-default-features --features 12-8-0
          - version: '12.5.0'
            flags: --no-default-features --features 12-5-0
          - version: '12.0.0'
            flags: --no-default-features
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ubuntu-18.04-stable-cargo-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --tests --manifest-path misskey-api/Cargo.toml ${{ matrix.flags }}
      - id: setup_env
        run: |
          cd ci/testenv
          docker-compose build
          docker-compose run --rm web yarn run init
          docker-compose up -d web
          docker-compose run --rm get-token
        env:
          MISSKEY_VERSION: ${{ matrix.version }}
      - uses: actions-rs/cargo@v1
        env:
          TEST_API_URL: http://localhost:3000/api/
          TEST_WEBSOCKET_URL: ws://localhost:3000/streaming
          TEST_ADMIN_TOKEN: ${{ steps.setup_env.outputs.admin_token }}
          TEST_USER_TOKEN: ${{ steps.setup_env.outputs.user_token }}
        with:
          command: test
          args: --manifest-path misskey-api/Cargo.toml ${{ matrix.flags }}
  fmt:
    name: Rustfmt
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
