on: [push, pull_request]

name: CI

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v3
      - run: cp ci/Cargo.lock ci/rust-toolchain.toml .
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --tests --locked
      - id: setup_env
        run: ./ci/testenv/setup.sh
        env:
          MISSKEY_IMAGE: 'misskey/misskey:13.10.3'
          MISSKEY_ID: aid
      - run: cargo test --features 13-10-3
        timeout-minutes: 15
        env:
          TEST_API_URL: http://localhost:3000/api/
          TEST_WEBSOCKET_URL: ws://localhost:3000/streaming
          TEST_ADMIN_TOKEN: ${{ steps.setup_env.outputs.admin_token }}
          TEST_USER_TOKEN: ${{ steps.setup_env.outputs.user_token }}
  fmt:
    name: Rustfmt
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: cp ci/Cargo.lock ci/rust-toolchain.toml .
      - run: cargo fmt --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: cp ci/Cargo.lock ci/rust-toolchain.toml .
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy -- -D warnings
