on: [push, pull_request]

name: CI

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: "ubuntu-20.04-default-cargo-all-${{ hashFiles('**/Cargo.toml') }}"
      - run: cargo build --tests
      - id: setup_env
        run: ./ci/testenv/setup.sh
        env:
          MISSKEY_IMAGE: 'misskey/misskey:12.75.1'
          MISSKEY_ID: aid
      - run: cargo test --features 12-75-0
        timeout-minutes: 15
        env:
          TEST_API_URL: http://localhost:3000/api/
          TEST_WEBSOCKET_URL: ws://localhost:3000/streaming
          TEST_ADMIN_TOKEN: ${{ steps.setup_env.outputs.admin_token }}
          TEST_USER_TOKEN: ${{ steps.setup_env.outputs.user_token }}
  fmt:
    name: Rustfmt
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy -- -D warnings
  minimal_version:
    name: Minimal versions build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: rustup override set nightly
      - uses: taiki-e/install-action@v1
        with:
          tool: cargo-hack@0.5.22
      - uses: taiki-e/install-action@v1
        with:
          tool: cargo-minimal-versions@0.1.7
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: "ubuntu-20.04-nightly-cargo-minimal-all-${{ hashFiles('**/Cargo.toml') }}"
      - run: cargo minimal-versions check --workspace --ignore-private
