on:
  schedule:
    - cron: '0 0 * * *'

name: Flaky

jobs:
  test_api:
    name: Test misskey-api and misskey-util
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      matrix:
        include:
          - image: 'misskey/misskey:13.11.0'
            flags: --features 13-11-0
          - image: 'misskey/misskey:13.10.3'
            flags: --features 13-10-3
          - image: 'misskey/misskey:13.10.0'
            flags: --features 13-10-0
          - image: 'misskey/misskey:13.9.0'
            flags: --features 13-9-0
          - image: 'misskey/misskey:13.8.0'
            flags: --features 13-8-0
          - image: 'misskey/misskey:13.7.0'
            flags: --features 13-7-0
          - image: 'misskey/misskey:13.4.0'
            flags: --features 13-4-0
          - image: 'misskey/misskey:13.3.2'
            flags: --features 13-3-2
          - image: 'misskey/misskey:13.3.0'
            flags: --features 13-3-0
          - image: 'misskey/misskey:13.2.5'
            flags: --features 13-2-4
          - image: 'misskey/misskey:13.2.3'
            flags: --features 13-2-3
          - image: 'misskey/misskey:13.1.1'
            flags: --features 13-1-1
          - image: 'misskey/misskey:13.1.0'
            flags: --features 13-1-0
          - image: 'misskey/misskey:13.0.0'
            flags: --features 13-0-0
          - image: 'misskey/misskey:12.112.3'
            flags: --features 12-112-3
          - image: 'misskey/misskey:12.112.2'
            flags: --features 12-112-0
          - image: 'misskey/misskey:12.111.0'
            flags: --features 12-111-0
          - image: 'misskey/misskey:12.109.2'
            flags: --features 12-109-0
          - image: 'misskey/misskey:12.108.1'
            flags: --features 12-108-0
          - image: 'misskey/misskey:12.107.0'
            flags: --features 12-107-0
          - image: 'misskey/misskey:12.106.0'
            flags: --features 12-106-0
          - image: 'misskey/misskey:12.105.0'
            flags: --features 12-105-0
          - image: 'misskey/misskey:12.102.0'
            flags: --features 12-102-0
          - image: 'misskey/misskey:12.99.1'
            flags: --features 12-99-0
          - image: 'misskey/misskey:12.98.0'
            flags: --features 12-98-0
          - image: 'misskey/misskey:12.97.0'
            flags: --features 12-96-0
          - image: 'misskey/misskey:12.95.0'
            flags: --features 12-95-0
          - image: 'misskey/misskey:12.93.0'
            flags: --features 12-93-0
          - image: 'misskey/misskey:12.92.0'
            flags: --features 12-92-0
          - image: 'misskey/misskey:12.91.0'
            flags: --features 12-91-0
          - image: 'misskey/misskey:12.89.1'
            flags: --features 12-89-1
          - image: 'misskey/misskey:12.89.0'
            flags: --features 12-89-0
          - image: 'misskey/misskey:12.88.0'
            flags: --features 12-88-0
          - image: 'misskey/misskey:12.82.0'
            flags: --features 12-82-0
          - image: 'misskey/misskey:12.81.0'
            flags: --features 12-81-0
          - image: 'misskey/misskey:12.80.0'
            flags: --features 12-80-0
          - image: 'misskey/misskey:12.79.2'
            flags: --features 12-79-2
          - image: 'misskey/misskey:12.79.0'
            flags: --features 12-79-0
          - image: 'misskey/misskey:12.77.1'
            flags: --features 12-77-1
          - image: 'misskey/misskey:12.77.0'
            flags: --features 12-77-0
          - image: 'misskey/misskey:12.75.0'
            flags: --features 12-75-0
          - image: 'misskey/misskey:12.71.0'
            flags: --features 12-71-0
          - image: 'misskey/misskey:12.70.0'
            flags: --features 12-70-0
          - image: 'misskey/misskey:12.69.0'
            flags: --features 12-69-0
          - image: 'misskey/misskey:12.68.0'
            flags: --features 12-67-0
          - image: 'misskey/misskey:12.66.0'
            flags: --features 12-66-0
          - image: 'misskey/misskey:12.65.4'
            flags: --features 12-65-4
          - image: 'misskey/misskey@sha256:9c13b1d240cef6f96aa19d133f0ddc5a927d7b8206b8656b940f3dc645ca0dbe'
            flags: --features 12-63-0
          - image: 'misskey/misskey:12.62.2'
            flags: --features 12-62-2
          - image: 'misskey/misskey:12.62.0'
            flags: --features 12-62-0
          - image: 'misskey/misskey:12.61.0'
            flags: --features 12-61-0
          - image: 'misskey/misskey:12.60.0'
            flags: --features 12-60-0
          - image: 'misskey/misskey:12.58.0'
            flags: --features 12-58-0
          - image: 'misskey/misskey:12.57.1'
            flags: --features 12-57-0
          - image: 'misskey/misskey:12.55.0'
            flags: --features 12-55-0
          - image: 'misskey/misskey:12.51.0'
            flags: --features 12-51-0
          - image: 'misskey/misskey:12.49.0'
            flags: --features 12-49-0
          - image: 'misskey/misskey:12.48.0'
            flags: --features 12-48-0
          - image: 'misskey/misskey:12.47.1'
            flags: --features 12-47-0
          - image: 'misskey/misskey:12.42.0'
            flags: --features 12-42-0
          - image: 'misskey/misskey:12.39.0'
            flags: --features 12-39-0
          - image: 'misskey/misskey:12.37.0'
            flags: --features 12-37-0
          - image: 'misskey/misskey:12.31.0'
            flags: --features 12-31-0
          - image: 'misskey/misskey:12.29.0'
            flags: --features 12-29-0
          - image: 'misskey/misskey:12.28.0'
            flags: --features 12-27-0
          - image: 'misskey/misskey:12.20.0'
            flags: --features 12-19-0
          - image: 'misskey/misskey:12.13.0'
            flags: --features 12-13-0
          - image: 'misskey/misskey:12.10.0'
            flags: --features 12-10-0
          - image: 'misskey/misskey:12.9.0'
            flags: --features 12-9-0
          - image: 'misskey/misskey:12.8.0'
            flags: --features 12-8-0
          - image: 'misskey/misskey:12.5.0'
            flags: --features 12-5-0
          - image: 'misskey/misskey:12.0.0'
            flags: ''
    steps:
      - uses: actions/checkout@v3
      - run: cp ci/Cargo.lock ci/rust-toolchain.toml .
      - uses: Swatinem/rust-cache@v2
      - name: Build misskey-api
        run: cargo build --tests --locked --manifest-path misskey-api/Cargo.toml ${{ matrix.flags }}
      - name: Build misskey-util
        run: cargo build --tests --locked --manifest-path misskey-util/Cargo.toml ${{ matrix.flags }}
      - id: setup_env
        run: ./ci/testenv/setup.sh
        env:
          MISSKEY_IMAGE: ${{ matrix.image }}
          MISSKEY_ID: aid
      - name: Test misskey-api
        run: cargo test --manifest-path misskey-api/Cargo.toml ${{ matrix.flags }}
        timeout-minutes: 5
        env:
          TEST_API_URL: http://localhost:3000/api/
          TEST_WEBSOCKET_URL: ws://localhost:3000/streaming
          TEST_ADMIN_TOKEN: ${{ steps.setup_env.outputs.admin_token }}
          TEST_USER_TOKEN: ${{ steps.setup_env.outputs.user_token }}
      - name: Test misskey-util
        run: cargo test --manifest-path misskey-util/Cargo.toml ${{ matrix.flags }}
        timeout-minutes: 5
        env:
          TEST_API_URL: http://localhost:3000/api/
          TEST_WEBSOCKET_URL: ws://localhost:3000/streaming
          TEST_ADMIN_TOKEN: ${{ steps.setup_env.outputs.admin_token }}
          TEST_USER_TOKEN: ${{ steps.setup_env.outputs.user_token }}
  test_id:
    name: Test misskey-api with different ID generation methods
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - method: meid
          - method: objectid
          - method: ulid
    steps:
      - uses: actions/checkout@v3
      - run: cp ci/Cargo.lock ci/rust-toolchain.toml .
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --tests --locked --manifest-path misskey-api/Cargo.toml --no-default-features --features "12-47-0 ${{ matrix.method }}"
      - id: setup_env
        run: ./ci/testenv/setup.sh
        env:
          MISSKEY_IMAGE: 'misskey/misskey:12.47.1'
          MISSKEY_ID: ${{ matrix.method }}
      - run: cargo test --manifest-path misskey-api/Cargo.toml --no-default-features --features "12-47-0 ${{ matrix.method }}"
        timeout-minutes: 5
        env:
          TEST_API_URL: http://localhost:3000/api/
          TEST_WEBSOCKET_URL: ws://localhost:3000/streaming
          TEST_ADMIN_TOKEN: ${{ steps.setup_env.outputs.admin_token }}
          TEST_USER_TOKEN: ${{ steps.setup_env.outputs.user_token }}
  test_websocket:
    name: Test misskey-websocket with different runtime
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      matrix:
        features:
          - tokio-runtime
          - async-std-runtime
    steps:
      - uses: actions/checkout@v3
      - run: cp ci/Cargo.lock ci/rust-toolchain.toml .
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --locked --tests --manifest-path misskey-websocket/Cargo.toml --no-default-features --features ${{ matrix.features }}
      - id: setup_env
        run: ./ci/testenv/setup.sh
        env:
          MISSKEY_IMAGE: 'misskey/misskey:12.0.0'
          MISSKEY_ID: aid
      - run: cargo test --manifest-path misskey-websocket/Cargo.toml --no-default-features --features ${{ matrix.features }}
        timeout-minutes: 3
        env:
          TEST_WEBSOCKET_URL: ws://localhost:3000/streaming
          TEST_USER_TOKEN: ${{ steps.setup_env.outputs.user_token }}
