on:
  push:
    tags: ['*']

name: release

jobs:
  upload:
    name: Upload to crates.io
    runs-on: ubuntu-20.04
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Publish misskey-core
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path misskey-core/Cargo.toml
      - name: Publish misskey-http
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path misskey-http/Cargo.toml
      - name: Publish misskey-websocket
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path misskey-websocket/Cargo.toml
      - name: Publish misskey-api
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path misskey-api/Cargo.toml
      - name: Publish misskey-util
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path misskey-util/Cargo.toml
      - name: Publish misskey
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path misskey/Cargo.toml
