on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

name: Unstable

jobs:
  test:
    name: Test with unstable toolchains
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - nightly
          - beta
    steps:
      - uses: actions/checkout@v3
      - run: cp ci/Cargo.lock .
      - run: rustup override set "$TOOLCHAIN"
        env:
          TOOLCHAIN: ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --tests --locked
      - id: setup_env
        run: ./ci/testenv/setup.sh
        env:
          MISSKEY_IMAGE: 'misskey/misskey:12.79.0'
          MISSKEY_ID: aid
      - run: cargo test --features 12-79-0
        timeout-minutes: 15
        env:
          TEST_API_URL: http://localhost:3000/api/
          TEST_WEBSOCKET_URL: ws://localhost:3000/streaming
          TEST_ADMIN_TOKEN: ${{ steps.setup_env.outputs.admin_token }}
          TEST_USER_TOKEN: ${{ steps.setup_env.outputs.user_token }}
  minimal_version:
    name: Minimal versions build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: rustup override set nightly
      - uses: taiki-e/install-action@v1
        with:
          tool: cargo-hack@0.5.22
      - uses: taiki-e/install-action@v1
        with:
          tool: cargo-minimal-versions@0.1.7
      - uses: Swatinem/rust-cache@v2
      - run: cargo minimal-versions check --workspace --ignore-private
